# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('total_converted_orgs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SIGNED_UP', 'Signed Up'), ('QUALIFIED', 'Qualified (Created Org / Added Property)'), ('REWARDED', 'Reward Granted'), ('FLAGGED', 'Flagged as Fraudulent / Duplicate')], default='SIGNED_UP', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
                ('code_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralcode')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('CREDIT', 'Subscription Credits (₹)'), ('AI_CREDITS', 'Ekrar AI Query Credits'), ('CASH_PAYOUT', 'Direct UPI / Bank Transfer')], default='CREDIT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PAID', 'Disbursed'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='referrals.referral')),
            ],
        ),
    ]
