# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(help_text='Phone number or email address', max_length=150)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp Official API'), ('EMAIL', 'Transactional Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App Notification')], max_length=20)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent to Gateway'), ('DELIVERED', 'Delivered'), ('READ', 'Read by Recipient'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=150)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENT', 'Rent & Invoicing'), ('PAYMENT', 'Payment Confirmation'), ('BOOKING', 'Booking Update'), ('AGREEMENT', 'Agreement & eSign'), ('KYC', 'KYC Verification'), ('COMPLAINT', 'Complaint Update'), ('VISITOR', 'Visitor Arrival'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
