# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('relation', models.CharField(blank=True, help_text='e.g. Parent, Friend, Colleague', max_length=50)),
                ('purpose', models.CharField(default='Visit', max_length=200)),
                ('expected_arrival', models.DateTimeField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested by Tenant'), ('APPROVED', 'Approved'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('REJECTED', 'Rejected by Security')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security_guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_visitors', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='tenants.tenancy')),
            ],
        ),
    ]
