# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Collection'), ('HELD', 'Held in Escrow / Ledger'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('SETTLED', 'Fully Settled & Closed')], default='PENDING', max_length=25)),
                ('collected_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_record', to='tenants.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='DepositSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damages_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unpaid_rent_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_transaction_reference', models.CharField(blank=True, max_length=100)),
                ('settlement_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='deposits.securitydeposit')),
            ],
        ),
    ]
