# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('RENT_REMINDER', 'Send Rent WhatsApp Reminders'), ('NOTICE_DISPATCH', 'Send Expiry Notice'), ('GENERATE_INVOICES', 'Bulk Generate Monthly Invoices'), ('MARK_VACANT', 'Update Bed Availability')], max_length=30)),
                ('preview_summary', models.TextField(help_text='Detailed preview shown to user before asking confirmation')),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared & Awaiting User Confirmation'), ('CONFIRMED', 'Confirmed & Executed'), ('CANCELLED', 'Cancelled by User'), ('FAILED', 'Execution Failed')], default='PREPARED', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai.aiconversation')),
            ],
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Ekrar AI Assistant'), ('SYSTEM', 'System')], max_length=15)),
                ('content', models.TextField()),
                ('tool_invocations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
        ),
    ]
