# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=50)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=10.0, help_text='INR per kWh unit', max_digits=6)),
                ('reading_date', models.DateField()),
                ('reading_image', models.ImageField(blank=True, null=True, upload_to='meter_photos/%Y/%m/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_readings', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_readings', to='properties.room')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('billing_month', models.IntegerField(help_text='Month number 1-12')),
                ('billing_year', models.IntegerField(default=2026)),
                ('base_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricity_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mess_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adjustments_or_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued / Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='ISSUED', max_length=20)),
                ('pdf_receipt', models.FileField(blank=True, null=True, upload_to='invoices/receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='RENT', max_length=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
        ),
    ]
