# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Block A, Main Wing', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon identifier, e.g. wifi, tv, wind', max_length=50)),
                ('category', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='e.g. Ground Floor, 1st Floor', max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='properties.building')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('property_type', models.CharField(choices=[('PG', 'PG (Paying Guest)'), ('HOSTEL', 'Hostel'), ('FLAT', 'Flat / Apartment'), ('ROOM', 'Private Room'), ('SHARED_ROOM', 'Shared Room'), ('STUDIO', 'Studio Apartment'), ('CO_LIVING', 'Co-Living Space'), ('VILLA', 'Independent House / Villa'), ('STUDENT_HOUSING', 'Student Housing'), ('WORKING_PROFESSIONAL', 'Working Professional Housing')], default='PG', max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nearby_landmarks', models.CharField(blank=True, max_length=255)),
                ('monthly_rent_starting', models.DecimalField(decimal_places=2, help_text='In INR (₹)', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('minimum_stay_months', models.IntegerField(default=1)),
                ('gender_preference', models.CharField(choices=[('ANY', 'Any / Co-ed'), ('MALE', 'Male Only (Boys)'), ('FEMALE', 'Female Only (Girls)'), ('FAMILY', 'Families Only')], default='ANY', max_length=20)),
                ('food_included', models.BooleanField(default=False)),
                ('food_type', models.CharField(blank=True, help_text='Veg, Non-Veg, Both', max_length=50)),
                ('electricity_policy', models.CharField(default='As per sub-meter reading (₹10/unit)', max_length=100)),
                ('water_policy', models.CharField(default='Included in rent', max_length=100)),
                ('house_rules', models.TextField(blank=True, default='No smoking inside rooms. Gate closes at 11:00 PM.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='organizations.organization')),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='properties.propertyamenity')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='properties.property'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, help_text='Remote or CDN image link', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_cover', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g. 101, 202-B', max_length=50)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Private Room'), ('DOUBLE', '2 Sharing / Double'), ('TRIPLE', '3 Sharing / Triple'), ('FOUR_SHARING', '4 Sharing'), ('STUDIO', 'Studio Flat'), ('1BHK', '1 BHK Unit'), ('2BHK', '2 BHK Unit'), ('3BHK', '3 BHK Unit'), ('DORMITORY', 'Dormitory')], default='DOUBLE', max_length=30)),
                ('furnishing', models.CharField(choices=[('UNFURNISHED', 'Unfurnished'), ('SEMI_FURNISHED', 'Semi-Furnished'), ('FULLY_FURNISHED', 'Fully Furnished')], default='FULLY_FURNISHED', max_length=20)),
                ('base_rent', models.DecimalField(decimal_places=2, help_text='Per person or entire room', max_digits=10)),
                ('default_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('has_attached_bathroom', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_identifier', models.CharField(help_text='e.g. Bed A, Bed B, Single', max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Under Maintenance'), ('NOTICE_PERIOD', 'On Notice')], db_index=True, default='AVAILABLE', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='properties.room')),
            ],
        ),
    ]
