# Generated by Django 5.1.15 on 2026-10-02 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_board_discom',
            field=models.CharField(blank=True, help_text='e.g. BESCOM, Torrent Power, TATA Power, BSES, MSEDCL, UGVCL', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_consumer_number',
            field=models.CharField(blank=True, help_text='DISCOM Consumer / CA / Service Connection Number', max_length=60),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_document_file',
            field=models.FileField(blank=True, null=True, upload_to='property_ownership_docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_document_type',
            field=models.CharField(blank=True, choices=[('ELECTRICITY_BILL', 'Electricity / Utility Bill'), ('PROPERTY_TAX_RECEIPT', 'Municipal Property Tax Challan'), ('SALE_DEED', 'Registered Sale Deed / Title Deed'), ('SOCIETY_MAINTENANCE_BILL', 'Society Maintenance Receipt'), ('POA_AUTHORIZATION', 'Power of Attorney / Authorization'), ('OTHER', 'Other Ownership Document')], default='ELECTRICITY_BILL', max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_verification_method',
            field=models.CharField(blank=True, choices=[('UTILITY_API', 'Instant Utility API (BBPS / DISCOM)'), ('DOCUMENT_UPLOAD', 'Document Review / OCR'), ('SELF_WARRANTY', 'Self Title Warranty & Undertaking')], default='UTILITY_API', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_warranty_accepted',
            field=models.BooleanField(default=False, help_text='Landlord accepts statutory title warranty under Indian law'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tax_id',
            field=models.CharField(blank=True, help_text='Municipal Property PID / Khata / Assessment Number', max_length=60),
        ),
    ]
