# Generated by Django 5.1.15 on 2026-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('SHOP_ADMIN', 'Shop Administrator'), ('SHOP_OPERATOR', 'Shop Operator'), ('OWNER', 'Property Owner / Landlord'), ('PROPERTY_MANAGER', 'Property Manager'), ('ACCOUNTANT', 'Accountant'), ('RECEPTIONIST', 'Receptionist'), ('SALES_EXECUTIVE', 'Sales Executive'), ('MAINTENANCE_STAFF', 'Maintenance Staff'), ('HOUSEKEEPING', 'Housekeeping'), ('TENANT', 'Tenant'), ('MESS_MANAGER', 'Mess Manager'), ('SECURITY', 'Security Guard')], default='TENANT', max_length=30, verbose_name='Primary Role'),
        ),
    ]
