# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_text', models.TextField(help_text='Standard agreement clauses with placeholders: {{tenant_name}}, {{owner_name}}, {{property_address}}, {{monthly_rent}}, {{deposit}}, etc.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='e.g. KA, MH, DL, TN, UP', max_length=5, unique=True)),
                ('state_name', models.CharField(max_length=100)),
                ('stamp_duty_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE_RENT', 'Percentage of Annual Rent'), ('SLAB', 'Slab Based')], default='FIXED', max_length=20)),
                ('base_stamp_duty', models.DecimalField(decimal_places=2, default=100.0, help_text='In INR (₹)', max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('e_stamping_supported', models.BooleanField(default=True)),
                ('legal_tenancy_act_reference', models.CharField(default='The Model Tenancy Act, 2021', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('state_code', models.CharField(default='KA', max_length=5)),
                ('stamp_duty_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=299.0, max_digits=10)),
                ('total_agreement_fee', models.DecimalField(decimal_places=2, default=399.0, max_digits=10)),
                ('agreement_html', models.TextField(blank=True)),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='agreements/pdf/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_OWNER_APPROVAL', 'Pending Owner Approval'), ('PENDING_TENANT_SIGN', 'Pending Tenant eSign'), ('PENDING_OWNER_SIGN', 'Pending Owner eSign'), ('STAMPING', 'Digital Stamping in Progress'), ('SIGNED', 'Signed & Executed'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('esign_provider_document_id', models.CharField(blank=True, max_length=150)),
                ('audit_trail_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='tenants.tenancy')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.agreementtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agreements.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(choices=[('OWNER', 'Landlord / Owner'), ('TENANT', 'Tenant'), ('WITNESS', 'Witness')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('sign_url', models.URLField(blank=True, max_length=500)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='agreements.agreement')),
            ],
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.stateconfiguration'),
        ),
    ]
