# Generated by Django 5.1.15 on 2026-09-29 16:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENT_PAYMENT', 'Rent Payment & Due Date'), ('SECURITY_DEPOSIT', 'Security Deposit & Refund'), ('MAINTENANCE', 'Society Maintenance'), ('ELECTRICITY_WATER', 'Electricity & Utilities'), ('LOCK_IN', 'Lock-in Period'), ('NOTICE_PERIOD', 'Notice Period & Vacating'), ('SOCIETY_RULES', 'Society Bylaws & Conduct'), ('PET_POLICY', 'Pet Policy'), ('REPAIRS', 'Structural & Internal Repairs'), ('COMMERCIAL_USE', 'Commercial Usage & GST'), ('TERMINATION', 'Default & Legal Eviction')], db_index=True, max_length=30)),
                ('title_en', models.CharField(max_length=200)),
                ('title_gu', models.CharField(help_text='Gujarati Clause Title', max_length=200)),
                ('content_en', models.TextField()),
                ('content_gu', models.TextField(help_text='Gujarati Unicode Legal Text')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'category'],
            },
        ),
        migrations.CreateModel(
            name='LegalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_index=True, default='GJ', max_length=5)),
                ('state_name', models.CharField(default='Gujarat', max_length=100)),
                ('district', models.CharField(blank=True, help_text='Optional district specific rule (e.g. Ahmedabad, Surat)', max_length=100)),
                ('agreement_type', models.CharField(choices=[('RESIDENTIAL', 'Residential Tenancy Agreement'), ('COMMERCIAL', 'Commercial Lease Deed'), ('AFFIDAVIT', 'Tenancy Affidavit & Undertaking')], default='RESIDENTIAL', max_length=30)),
                ('property_type', models.CharField(default='ANY', max_length=50)),
                ('min_duration_months', models.IntegerField(default=1)),
                ('max_duration_months', models.IntegerField(default=60)),
                ('fixed_stamp_duty', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('rate_percentage', models.DecimalField(decimal_places=3, default=0.25, help_text='Percentage of total average annual rent if applicable', max_digits=5)),
                ('minimum_stamp_duty', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('registration_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_fee_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('registration_required_threshold_months', models.IntegerField(default=12, help_text='Leases >= this duration require mandatory sub-registrar registration')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=299.0, max_digits=10)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='GJ-2026-V1', max_length=30)),
                ('notes', models.TextField(blank=True, default='Gujarat Stamp Act 1958 Schedule I Article 30')),
                ('source_reference', models.CharField(default='Gujarat Stamp Act 1958 Schedule I Article 30', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='agreementevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential Tenancy Agreement'), ('COMMERCIAL', 'Commercial Lease Agreement'), ('AFFIDAVIT', 'Tenancy Affidavit')], default='RESIDENTIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='agreement',
            name='change_request_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='creator_type',
            field=models.CharField(choices=[('OWNER', 'Property Owner'), ('TENANT', 'Tenant'), ('SHOP', 'Shop / Kiosk Assisted')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='current_version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agreement',
            name='document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 Hash of executed PDF', max_length=64),
        ),
        migrations.AddField(
            model_name='agreement',
            name='duration_months',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='agreement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='escalation_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='agreement',
            name='esign_provider',
            field=models.CharField(default='MOCK_ESIGN', max_length=50),
        ),
        migrations.AddField(
            model_name='agreement',
            name='esign_status',
            field=models.CharField(default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GU', 'Gujarati'), ('BILINGUAL', 'Bilingual (Gujarati + English)')], default='BILINGUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='lock_in_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='agreement',
            name='maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notice_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='agreement',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='properties.property'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_category',
            field=models.CharField(default='2BHK Residential Flat', max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_city',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_pincode',
            field=models.CharField(default='380009', max_length=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
        migrations.AddField(
            model_name='agreement',
            name='property_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='provider_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='public_verification_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='registration_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreement',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='special_clauses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stamp_certificate_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stamp_certificate_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stamp_provider',
            field=models.CharField(default='GUJARAT_ESTAMP', max_length=50),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stamp_status',
            field=models.CharField(default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='stamp_duty_amount',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='state_code',
            field=models.CharField(default='GJ', max_length=5),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OWNER_DETAILS_PENDING', 'Owner Details Pending'), ('TENANT_DETAILS_PENDING', 'Tenant Details Pending'), ('INVITATION_SENT', 'Invitation Sent to Counterparty'), ('TENANT_ACCEPTED', 'Tenant Accepted Terms'), ('OWNER_VERIFICATION_PENDING', 'Owner Identity Verification Pending'), ('TENANT_VERIFICATION_PENDING', 'Tenant Identity Verification Pending'), ('BOTH_VERIFIED', 'Both Parties Verified'), ('REVIEW_PENDING', 'Agreement Review Pending'), ('OWNER_SIGNING', 'Awaiting Owner Digital Signature'), ('TENANT_SIGNING', 'Awaiting Tenant Digital Signature'), ('BOTH_SIGNED', 'Both Parties Signed'), ('STAMPING_PENDING', 'Govt e-Stamping in Progress'), ('STAMPED', 'e-Stamped by State Treasury'), ('REGISTRATION_REQUIRED', 'Sub-Registrar Registration Required'), ('REGISTRATION_PENDING', 'Registration Case in Progress'), ('REGISTERED', 'Officially Registered'), ('COMPLETED', 'Completed & Legally Executed'), ('CHANGE_REQUESTED', 'Changes Requested by Party'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Execution Failed')], db_index=True, default='DRAFT', max_length=35),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='tenants.tenancy'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='total_agreement_fee',
            field=models.DecimalField(decimal_places=2, default=699.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agreementevent',
            name='event_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stateconfiguration',
            name='base_stamp_duty',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='In INR (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stateconfiguration',
            name='legal_tenancy_act_reference',
            field=models.CharField(default='The Gujarat Tenancy Act & Model Tenancy Act, 2021', max_length=255),
        ),
        migrations.AlterField(
            model_name='stateconfiguration',
            name='state_code',
            field=models.CharField(help_text='e.g. GJ, KA, MH, DL, TN, UP', max_length=5, unique=True),
        ),
        migrations.CreateModel(
            name='AgreementInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('target_role', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('target_name', models.CharField(max_length=150)),
                ('target_email', models.EmailField(max_length=254)),
                ('target_phone', models.CharField(max_length=15)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='agreements.agreement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Assisted Session'), ('COMPLETED', 'Completed Successfully'), ('EXPIRED', 'Session Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('device_metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_sessions', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_owner_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_tenant_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='kiosk_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='agreements.kiosksession'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='rule_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.legalrule'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, default='Ahmedabad', max_length=100)),
                ('district', models.CharField(default='Ahmedabad', max_length=100)),
                ('state', models.CharField(default='Gujarat', max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_per_agreement', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kiosksession',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agreements.shop'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='agreements.shop'),
        ),
        migrations.CreateModel(
            name='AgreementParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('aadhaar_masked', models.CharField(blank=True, help_text='e.g. XXXX-XXXX-1234', max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Verification In Progress'), ('VERIFIED', 'Identity Verified'), ('REJECTED', 'Verification Rejected')], default='UNVERIFIED', max_length=20)),
                ('verification_provider', models.CharField(default='AADHAAR_OTP', max_length=50)),
                ('verification_reference', models.CharField(blank=True, max_length=150)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('signing_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('INVITATION_SENT', 'Invitation Sent'), ('SIGNED', 'Digitally Signed'), ('REJECTED', 'Signature Rejected')], default='NOT_STARTED', max_length=20)),
                ('signing_provider', models.CharField(default='MOCK_ESIGN', max_length=50)),
                ('sign_url', models.URLField(blank=True, max_length=500)),
                ('signature_reference', models.CharField(blank=True, max_length=150)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='agreements.agreement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agreement', 'party_type')},
            },
        ),
        migrations.CreateModel(
            name='AgreementVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('document_html', models.TextField()),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('change_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agreements.agreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('agreement', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ShopOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='agreements.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop', 'user')},
            },
        ),
    ]
