# Generated by Django 5.1.15 on 2026-09-29 18:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreementclause_legalrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementclause',
            name='content_hi',
            field=models.TextField(blank=True, help_text='Hindi Unicode Legal Text'),
        ),
        migrations.AddField(
            model_name='agreementclause',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Hindi Clause Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('GU', 'Gujarati'), ('HI', 'Hindi'), ('BILINGUAL', 'Bilingual (Gujarati + English)'), ('BILINGUAL_HI', 'Bilingual (Hindi + English)'), ('TRILINGUAL', 'Trilingual (Gujarati + Hindi + English)')], default='BILINGUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='AgreementCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiator_role', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('cancellation_reason', models.TextField()),
                ('notice_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField()),
                ('mutual_consent', models.BooleanField(default=False)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='agreements/cancellations/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Notice Served / Pending Review'), ('MUTUALLY_AGREED', 'Mutually Agreed'), ('EXECUTED', 'Termination Executed'), ('CONTESTED', 'Contested by Counterparty')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='agreements.agreement')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total Payable INR', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('government_amount', models.DecimalField(decimal_places=2, default=300.0, help_text='Gujarat State Treasury Stamp Duty', max_digits=10)),
                ('platform_amount', models.DecimalField(decimal_places=2, default=299.0, help_text='eRentKarar Platform Fee', max_digits=10)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='eStamp & eSign CRA Procurement', max_digits=10)),
                ('gateway_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Payment Gateway Fee', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Statutory GST (18%)', max_digits=10)),
                ('courier_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Physical delivery fee if chosen', max_digits=10)),
                ('shop_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Assisted Kiosk Partner Share', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('gateway', models.CharField(default='RAZORPAY', max_length=50)),
                ('gateway_order_id', models.CharField(blank=True, max_length=150)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=150)),
                ('invoice_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_payments', to='agreements.agreement')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_agreement_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementRenewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revised_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revised_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_duration_months', models.IntegerField(default=11)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Renewal Requested'), ('MUTUAL_CONSENT', 'Mutual Terms Agreed'), ('EXECUTED', 'New Deed Executed'), ('REJECTED', 'Renewal Declined')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='agreements.agreement')),
                ('renewed_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='agreements.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('delivery_address', models.TextField()),
                ('city', models.CharField(default='Ahmedabad', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(default='Gujarat', max_length=50)),
                ('provider', models.CharField(default='SPEED_POST', help_text='e.g. India Post Speed Post, BlueDart, Delhivery', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ORDERED', 'Order Placed'), ('DISPATCHED', 'Dispatched from Hub'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered to Doorstep'), ('RETURNED', 'Returned to Sender')], default='ORDERED', max_length=20)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='agreements.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='LegalNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('recipient_role', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('notice_type', models.CharField(choices=[('RENT_DEFAULT', 'Notice for Non-Payment of Rent'), ('NOTICE_TO_VACATE', 'Notice to Vacate (Expiry / Breach)'), ('LEASE_BREACH', 'Notice of Breach of Covenant'), ('SECURITY_REFUND_CLAIM', 'Demand for Refund of Security Deposit')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dispatch_mode', models.CharField(choices=[('DIGITAL', 'Digital Delivery (Email, SMS & WhatsApp)'), ('SPEED_POST', 'Registered Speed Post AD'), ('ADVOCATE_SERVED', 'Served via Practicing Advocate')], default='DIGITAL', max_length=20)),
                ('postal_tracking_number', models.CharField(blank=True, max_length=100)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_notices', to='agreements.agreement')),
            ],
        ),
        migrations.CreateModel(
            name='SigningTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('OWNER', 'Property Owner / Landlord (First Party)'), ('TENANT', 'Tenant (Second Party)')], max_length=20)),
                ('provider', models.CharField(default='MOCK_ESIGN', max_length=50)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Signature'), ('SIGNED', 'Successfully Signed'), ('EXPIRED', 'Sign URL Expired'), ('FAILED', 'Signing Failed')], default='PENDING', max_length=20)),
                ('sign_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response_reference', models.CharField(blank=True, max_length=200)),
                ('document_hash_before_sign', models.CharField(blank=True, max_length=64)),
                ('document_hash_after_sign', models.CharField(blank=True, max_length=64)),
                ('audit_reference', models.CharField(blank=True, max_length=200)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_transactions', to='agreements.agreement')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_transactions', to='agreements.agreementparty')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='AADHAAR_PROVIDER', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=150)),
                ('verification_type', models.CharField(choices=[('AADHAAR_OTP', 'Aadhaar OTP Verification'), ('AADHAAR_EKYC', 'Aadhaar eKYC (Biometric / OTP)'), ('AADHAAR_OFFLINE_KYC', 'Aadhaar Paperless Offline e-KYC (XML)'), ('DIGITAL_KYC', 'Authorized Digital KYC Provider')], default='AADHAAR_OTP', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Verification In Progress'), ('VERIFIED', 'Successfully Verified'), ('FAILED', 'Verification Failed')], db_index=True, default='PENDING', max_length=20)),
                ('masked_aadhaar', models.CharField(help_text='e.g. XXXX-XXXX-1234', max_length=20)),
                ('verified_name', models.CharField(blank=True, max_length=150)),
                ('verified_dob', models.CharField(blank=True, max_length=20)),
                ('verified_gender', models.CharField(blank=True, max_length=10)),
                ('verified_address_reference', models.TextField(blank=True)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
