# Generated by Django 5.1.15 on 2026-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreementclause_content_hi_agreementclause_title_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentityverification',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useridentityverification',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentityverification',
            name='consent_version',
            field=models.CharField(default='v1.0-2026', max_length=50),
        ),
        migrations.AddField(
            model_name='useridentityverification',
            name='purpose',
            field=models.CharField(default='Rental Agreement Identification & e-KYC under IT Act 2000', max_length=255),
        ),
        migrations.AlterField(
            model_name='useridentityverification',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('OTP_SENT', 'OTP Dispatched to UIDAI Mobile'), ('OTP_VERIFIED', 'OTP Verified'), ('VERIFIED', 'Successfully Verified'), ('FAILED', 'Verification Failed'), ('EXPIRED', 'Verification Expired'), ('CANCELLED', 'Verification Cancelled'), ('PENDING', 'Verification In Progress')], db_index=True, default='NOT_STARTED', max_length=20),
        ),
    ]
