# Generated by Django 5.1.15 on 2026-10-05 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_alter_useridentityverification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='advance_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='amendment_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='agreements.agreement'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='financial_terms_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='financial_terms_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='is_immutable',
            field=models.BooleanField(default=False, help_text='Locked once executed. Cannot be silently edited.'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='landlord_declaration_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='landlord_declaration_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_advocate_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='notary_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('PENDING', 'Pending Notary Review'), ('COMPLETED', 'Notarization Completed'), ('FAILED', 'Notarization Failed')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='agreement',
            name='police_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreement',
            name='police_verification_document',
            field=models.FileField(blank=True, null=True, upload_to='agreements/police/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='police_verification_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='police_verification_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('REQUESTED', 'Requested'), ('DOCUMENTS_SUBMITTED', 'Documents Submitted'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('REFERENCE_GENERATED', 'Reference Generated'), ('PROCESSING', 'Processing at Police Station'), ('COMPLETED', 'Police Verification Completed'), ('REJECTED', 'Police Verification Rejected'), ('FAILED', 'Verification Failed')], default='NOT_REQUESTED', max_length=30),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stamped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_declaration_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_declaration_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='document_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='new_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='new_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='previous_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='previous_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='signature_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='stamp_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='legalrule',
            name='calculation_method',
            field=models.CharField(default='FIXED_OR_PERCENTAGE', help_text='FIXED, PERCENTAGE, FIXED_OR_PERCENTAGE, SLAB', max_length=50),
        ),
        migrations.AddField(
            model_name='legalrule',
            name='maximum_stamp_duty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='legalrule',
            name='supported',
            field=models.BooleanField(default=True, help_text='True if this jurisdiction is tested and supported'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DATA_VALIDATED', 'Data Validated'), ('PARTIES_INVITED', 'Parties Invited'), ('PARTIES_VERIFIED', 'Parties Identity Verified'), ('AGREEMENT_FINALIZED', 'Agreement Terms Finalized'), ('STAMP_DUTY_CALCULATED', 'Stamp Duty Calculated'), ('STAMP_PAYMENT_PENDING', 'Stamp Payment Pending'), ('STAMP_PAYMENT_SUCCESS', 'Stamp Payment Successful'), ('ESTAMP_REQUESTED', 'e-Stamp Certificate Requested'), ('ESTAMP_ISSUED', 'e-Stamp Certificate Issued'), ('ESIGN_PENDING', 'Electronic Signature Pending'), ('LANDLORD_SIGNED', 'Landlord Signed'), ('TENANT_SIGNED', 'Tenant Signed'), ('EXECUTED', 'Executed & Sealed'), ('REGISTRATION_REQUIRED', 'Sub-Registrar Registration Required'), ('REGISTRATION_PENDING', 'Registration Case in Progress'), ('REGISTERED', 'Officially Registered'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Execution Failed'), ('OWNER_DETAILS_PENDING', 'Owner Details Pending'), ('TENANT_DETAILS_PENDING', 'Tenant Details Pending'), ('INVITATION_SENT', 'Invitation Sent to Counterparty'), ('TENANT_ACCEPTED', 'Tenant Accepted Terms'), ('OWNER_VERIFICATION_PENDING', 'Owner Identity Verification Pending'), ('TENANT_VERIFICATION_PENDING', 'Tenant Identity Verification Pending'), ('BOTH_VERIFIED', 'Both Parties Verified'), ('REVIEW_PENDING', 'Agreement Review Pending'), ('OWNER_SIGNING', 'Awaiting Owner Digital Signature'), ('TENANT_SIGNING', 'Awaiting Tenant Digital Signature'), ('BOTH_SIGNED', 'Both Parties Signed'), ('STAMPING_PENDING', 'Govt e-Stamping in Progress'), ('STAMPED', 'e-Stamped by State Treasury'), ('COMPLETED', 'Completed & Legally Executed'), ('CHANGE_REQUESTED', 'Changes Requested by Party')], db_index=True, default='DRAFT', max_length=35),
        ),
    ]
