# Generated by Django 5.1.15 on 2026-10-05 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_agreement_advance_rent_agreement_amendment_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementPricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soft_copy_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hard_copy_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='Additional fee for physical hard copy courier', max_digits=10)),
                ('printing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('courier_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('partner_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=1499.0, help_text='Base agreement execution package fee', max_digits=10)),
                ('expected_sla_days', models.IntegerField(default=7, help_text='Estimated completion days (default 7)')),
                ('sla_display_text', models.CharField(default='Expected completion within 7 days.', help_text='Display text for customer estimate', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agreement Pricing Configuration',
                'verbose_name_plural': 'Agreement Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='AgreementOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('delivery_type', models.CharField(choices=[('SOFT_COPY', 'Soft Copy (Digital PDF & Email)'), ('HARD_COPY', 'Hard Copy (Physical Printed Copy by Courier)')], default='SOFT_COPY', max_length=20)),
                ('status', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('DOCUMENTS_RECEIVED', 'Documents Received'), ('PARTNER_ASSIGNMENT_PENDING', 'Partner Assignment Pending'), ('PARTNER_ASSIGNED', 'Partner Assigned'), ('DOCUMENT_REVIEW', 'Document Review'), ('CORRECTION_REQUIRED', 'Correction Required'), ('AGREEMENT_PROCESSING', 'Agreement Processing'), ('STAMPING_IN_PROGRESS', 'Stamping In Progress'), ('STAMPING_COMPLETED', 'Stamping Completed'), ('FINAL_DOCUMENT_PENDING', 'Final Document Pending'), ('FINAL_DOCUMENT_READY', 'Final Agreement Ready'), ('DELIVERY_TYPE_SELECTED', 'Delivery Type Selected'), ('EMAIL_DELIVERY_PENDING', 'Email Delivery Pending'), ('EMAIL_DELIVERED', 'Email Delivered'), ('PRINTING_PENDING', 'Printing Pending'), ('PRINTED', 'Printed'), ('COURIER_PENDING', 'Courier Pending'), ('COURIER_BOOKED', 'Courier Booked'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], db_index=True, default='ORDER_CREATED', max_length=40)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100)),
                ('delivery_state', models.CharField(blank=True, max_length=50)),
                ('delivery_pincode', models.CharField(blank=True, max_length=10)),
                ('service_amount', models.DecimalField(decimal_places=2, default=1499.0, max_digits=10)),
                ('hard_copy_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('courier_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('printing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=1499.0, max_digits=10)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('payment_order_id', models.CharField(blank=True, max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_completion_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('partner_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('partner_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('internal_notes', models.TextField(blank=True)),
                ('qc_status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('qc_notes', models.TextField(blank=True)),
                ('qc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_document', models.FileField(blank=True, null=True, upload_to='agreements/final_orders/%Y/%m/')),
                ('final_document_hash', models.CharField(blank=True, max_length=64)),
                ('document_version', models.IntegerField(default=1)),
                ('courier_provider', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('correction_requested', models.BooleanField(default=False)),
                ('correction_reason', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_orders', to='agreements.agreement')),
                ('assigned_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agreement_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_agreement_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LANDLORD_ID', 'Landlord Identity Proof (Aadhaar / Voter ID)'), ('LANDLORD_ADDRESS', 'Landlord Address Proof'), ('TENANT_ID', 'Tenant Identity Proof (Aadhaar / Passport)'), ('TENANT_ADDRESS', 'Tenant Address Proof'), ('PROPERTY_DOC', 'Property Document (Index II / Electricity Bill / Tax Receipt)'), ('OTHER', 'Other Supporting Document')], max_length=50)),
                ('file', models.FileField(upload_to='agreements/documents/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('MISSING', 'Missing'), ('INVALID', 'Invalid')], default='UPLOADED', max_length=20)),
                ('validation_notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agreements.agreement')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agreements.agreementorder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_customer_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agreements.agreementorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
