# Generated by Django 5.1.15 on 2026-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_agreementpricingconfig_agreementorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementdocument',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified by admin'), ('UPLOADED', 'Pending verification'), ('MISSING', 'Missing'), ('INVALID', 'Invalid')], default='UPLOADED', max_length=20),
        ),
    ]
