# Generated by Django 5.1.15 on 2026-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0008_alter_agreementdocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementpayment',
            name='checkout_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
