# Generated by Django 5.1.15 on 2026-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0009_agreementpayment_checkout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementpricingconfig',
            name='commercial_fee',
            field=models.DecimalField(decimal_places=2, default=2199.0, help_text='Commercial base agreement package fee (₹2199)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='agreementpricingconfig',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=1499.0, help_text='Individual / Residential base agreement package fee (₹1499)', max_digits=10),
        ),
    ]
