# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='NOT_SUBMITTED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_records', to='tenants.tenancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR_FRONT', 'Aadhaar Card (Front)'), ('AADHAAR_BACK', 'Aadhaar Card (Back)'), ('PAN_CARD', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving Licence'), ('VOTER_ID', 'Voter ID'), ('POLICE_VERIFICATION', 'Police Verification Certificate'), ('STUDENT_EMP_ID', 'Student / Employee ID')], max_length=30)),
                ('masked_document_number', models.CharField(blank=True, help_text='e.g. XXXX-XXXX-4589 or ABCDE****F', max_length=30)),
                ('document_file', models.FileField(upload_to='kyc_documents/%Y/%m/')),
                ('mime_type', models.CharField(default='application/pdf', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kyc')),
            ],
        ),
    ]
