# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Onboarding'), ('ACTIVE', 'Active Stay'), ('NOTICE', 'Under Notice Period'), ('VACATED', 'Vacated & Settled'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='properties.bed')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='properties.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField()),
                ('expected_vacate_date', models.DateField()),
                ('actual_vacate_date', models.DateField(blank=True, null=True)),
                ('final_meter_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('damages_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unpaid_dues_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Move-out Requested'), ('INSPECTION_PENDING', 'Inspection Pending'), ('SETTLEMENT_PENDING', 'Settlement Pending'), ('COMPLETED', 'Completed & Refunded')], default='REQUESTED', max_length=25)),
                ('settlement_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='move_out_record', to='tenants.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='MoveIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_move_in_date', models.DateField()),
                ('meter_reading_electricity', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('keys_handed_over', models.BooleanField(default=True)),
                ('room_condition_notes', models.TextField(blank=True)),
                ('verified_by_staff', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='move_in_record', to='tenants.tenancy')),
            ],
        ),
    ]
