# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('bookings', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('RENT', 'Monthly Rent'), ('TOKEN', 'Booking Token'), ('SECURITY_DEPOSIT', 'Security Deposit'), ('MAINTENANCE', 'Maintenance'), ('UTILITY', 'Utility Bill'), ('MESS', 'Mess / Food'), ('AGREEMENT_FEE', 'Agreement & Stamping Fee'), ('OTHER', 'Other Charges')], default='RENT', max_length=30)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI (PhonePe, GPay, Paytm)'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('NETBANKING', 'Net Banking'), ('CASH', 'Cash / Offline')], default='UPI', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Order Created'), ('PENDING', 'Pending Confirmation'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('gateway_name', models.CharField(default='RAZORPAY', max_length=50)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='organizations.organization')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tenants.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(blank=True, help_text='Webhook Idempotency ID', max_length=150, null=True, unique=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('response_code', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
        ),
    ]
