# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing & Water'), ('ELECTRICAL', 'Electrical & Wiring'), ('CARPENTRY', 'Carpentry & Furniture'), ('APPLIANCE', 'Geyser / AC / RO Appliance'), ('CLEANING', 'Room / Washroom Cleaning'), ('WIFI', 'Internet & WiFi'), ('FOOD', 'Mess / Food Quality'), ('NOISE', 'Noise & Disturbance'), ('SECURITY', 'Safety & Security'), ('OTHER', 'Other')], max_length=30)),
                ('urgency', models.CharField(choices=[('LOW', 'Low (Within 3 days)'), ('MEDIUM', 'Medium (Within 24 hours)'), ('HIGH', 'High (Urgent, within 6 hours)'), ('EMERGENCY', 'Emergency (Immediate)')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/')),
                ('status', models.CharField(choices=[('OPEN', 'Open / Reported'), ('ASSIGNED', 'Assigned to Technician'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting on Parts'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Confirmed & Closed by Tenant')], db_index=True, default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='properties.property')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tenants.tenancy')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('vendor_phone', models.CharField(blank=True, max_length=15)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to='maintenance_bills/%Y/%m/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_record', to='complaints.complaint')),
            ],
        ),
    ]
