# Generated by Django 5.1.15 on 2026-09-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 3 Meals / Day (Veg + Non-Veg)', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_plans', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='MealAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=20)),
                ('is_opted_out', models.BooleanField(default=False, help_text='Tenant opted out 3 hours before to avoid wastage')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_attendance', to='tenants.tenancy')),
            ],
            options={
                'unique_together': {('tenancy', 'meal_date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('breakfast', models.CharField(help_text='e.g. Idli Vada Sambar, Tea/Coffee', max_length=255)),
                ('lunch', models.CharField(help_text='e.g. Rice, Dal Tadka, Paneer Butter Masala, Roti, Curd', max_length=255)),
                ('dinner', models.CharField(help_text='e.g. Roti, Chicken Curry / Mixed Veg, Rice, Gulab Jamun', max_length=255)),
                ('special_item', models.CharField(blank=True, max_length=150)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_menu', to='properties.property')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('property', 'day_of_week')},
            },
        ),
    ]
